services:
  app:
    build:
      context: ../..
      dockerfile: mcp_host/decimer/Dockerfile
    ports:
      - "${MCP_PORT}:${MCP_PORT}"
    environment:
      - MCP_PORT=${MCP_PORT}
      - ENV=production
    volumes:
      - ../../${WORKSPACE_PATH}:/workspace:rw
      - ./models:/app/models
