services:
  xcmsrocker:
    platform: linux/amd64 # Force platform compatibility (mac os and arm architecture ...)
    image: yufree/xcmsrocker:latest
    container_name: xcmsrocker
    environment:
      - PASSWORD=xcmsrocker  # Set the password for RStudio Server
    ports:
      - "8787:8787"         # Map host port 8787 to container port 8787
    working_dir: /app
    volumes:
      - ./rstudio_data:/home/rstudio  # Persist RStudio data (optional)
      - "../../:/app"
    restart: unless-stopped  # Auto-restart unless manually stopped