services:
  xcmsrocker:
    platform: linux/amd64 # Force platform compatibility (mac os and arm architecture ...)
    build:
      context: ../..
      dockerfile: mcp_host/Rscript/Dockerfile
    container_name: xcmsrocker
    environment:
      - MCP_PORT=${MCP_PORT}
      - PASSWORD=xcmsrocker  # Set the password for RStudio Server (optional)
    ports:
      - "${MCP_PORT}:${MCP_PORT}"  # MCP server port
      - "8787:8787"                # RStudio Server port (optional)
    volumes:
      - ./rstudio_data:/home/rstudio  # Persist RStudio data (optional)
      - ../../workspace:/app/workspace:rw  # Shared workspace
    restart: unless-stopped  # Auto-restart unless manually stopped
